package com.seleniumproject.day06;

import com.utils.TestBase;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class C01_Alerts extends TestBase {
    /*
 What is an alert?
 - Alerts are webElements generated by javascript alerts. e.g. when clicking a button, we can see informative alerts.
 - When there's an alert, we must handle it first to continue the test execution.
 - We cannot inspect alerts, but we can handle them by switching to alerts first.
 - driver.switchTo(). either accept(), dismiss(), getText() or sendKeys().

   Alerts are a pop up that is generated by javascript.
   When there is an alert, we must handle the alerts.
   Otherwise, we cannot continue to the test execution
   How do you handle alert?
          First we cannot inspect js alerts. We should first switch
          to the alert and use accept() to click ok, dismiss() to
          click cancel, sendKeys() to type, getText() to get the
          text from the alert
 */

    @Test
    public void acceptAlert() throws InterruptedException {
        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
        // driver.findElement(By.className("btn")).click();
        // driver.findElement(By.xpath("//button[@class='btn btn-primary']")).click();
        driver.findElement(By.xpath("//button[@onclick='jsAlert()']")).click();

//      Verify that alert has text "I am a JS Alert"
        String actualAlertText = driver.switchTo().alert().getText();
        System.out.println("actualAlertText = " + actualAlertText);

        //Assertion
        assertEquals("I am a JS Alert" , actualAlertText);
        Thread.sleep(3000);

        // Click ok
        driver.switchTo().alert().accept();

        // Verify that alert ia handled successfully
        String resultText = driver.findElement(By.id("result")).getText();
        assertEquals("You successfully clicked an alert" , resultText);


    }

    @Test
    public void dismissAlert() throws InterruptedException {
        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
        driver.findElement(By.xpath("//button[@onclick='jsConfirm()']")).click();

        // Verify text "I am a JS Confirm" is visible

        String actualAlertText = driver.switchTo().alert().getText();
        assertEquals("I am a JS Confirm", actualAlertText);
        Thread.sleep(3000);

        // Click on cancel
        driver.switchTo().alert().dismiss();
        Thread.sleep(3000);

        // Verify that alert is handles successfully
        String actualResult = driver.findElement(By.id("result")).getText();
        assertEquals("You clicked: Cancel", actualResult);


    }

    @Test
    public void promptAlert() throws InterruptedException {

        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
        driver.findElement(By.xpath("//button[@onclick='jsPrompt()']")).click();

        // Verify text "I am a JS prompt" is visible

        String actualAlertText = driver.switchTo().alert().getText();
        assertEquals("I am a JS prompt", actualAlertText);
        Thread.sleep(3000);

        // Type something and accept it
        driver.switchTo().alert().sendKeys("Hello World!");
        Thread.sleep(3000);

        driver.switchTo().alert().accept();

        Thread.sleep(3000);

        // Verify that alert is handles successfully
        String actualResult = driver.findElement(By.id("result")).getText();
        assertEquals("You entered: Hello World!", actualResult);


    }


}
